export * from './state.model';
export * from './address.model';
export * from './paginator.model';
export * from './response';
export * from './detailsPerson.model';
export * from './organization.model';
export * from './contact.model';
export * from './phones.model';
export * from './detailsDevice.model';
